#:schema node_modules/wrangler/config-schema.json
name = "smail"
compatibility_date = "2024-09-25"
main = "app/worker.ts"
assets = { directory = "./build/client" }

[observability]
enabled = true

[[kv_namespaces]]
binding = "KV"
id = "defce78d98ad45d59be86c8daa19f509"

[[d1_databases]]
binding = "DB"
database_name = "smail"
database_id = "6e2a9616-4afc-478c-90bb-fd3ec57e0d18"
preview_database_id = "f591d1c7-0060-4d35-a146-099ec27b49b1"
migrations_dir = "app/drizzle"
